export const stateList = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const ageGrpList = [
  "10-19",
  "20-29",
  "30-39",
  "40-49",
  "50-59",
  "60-69",
  "70-79",
  "80-89",
  "90-99",
  "100-109",
];

export const genderList = [
  "Male",
  "Female",
  "Gay",
  "Bisexual",
  "Lesbian",
  "Straight",
  "Transgender",
  "LBGTQ+ ",
  "Other",
];

export const educationList = [
  "Less than HS Diploma or GED",
  "HS Diploma or GED",
  "Trade Certification",
  "Associates degree",
  "Bachelors degree",
  "Masters degree",
  "Doctorate",
  "Other",
];

export const raceList = [
  "American Indian/Alaskan Native",
  "Asian American",
  "Black/African American",
  "Hispanic/Latino American",
  "Native Hawaiian/Pacific Islander",
  "White",
  "Multiracial",
  "Other",
];
