export const dummyPersonalityInfo = {
    hobbies: ["Reading"],
    sports: ["Basketball"],
    likes: ["Traveling"],
    personality: ["Outgoing"],
    bookGenres: ["Fiction"],
    musicGenres: ["Rock"],
    movieGenres: ["Action"],
};

export const dummyBasicInfo = {
    firstName: "John",
    lastName: "Doe",
    inmateNumber: "123456",
    age: "30",
    gender: "Male",
    orientation: "Straight",
    state: ["California"],
    city: "Los Angeles",
    mailingAddress: "1234 Main St",
    zipcode: "90001",
    dateOfBirth: "1993-01-01",
    height: "6'0\"",
    weight: "180 lbs",
    hairColor: ["Brown"],
    eyeColor: ["Blue"],
    race: ["Other"],
    spokenLanguages: "English",
    institutionalEmailProvider: ["example.com"],
    religiousPref: ["Christian"],
    highSchool: "Lincoln High",
    highSchoolState: "California",
    highSchoolCity: "Los Angeles",
    education: ["Bachelors degree"],
    college: "University of California",
    collegeState: "California",
    collegeCity: "Los Angeles",
    homeTownCity: "San Francisco",
    homeTownState: "California",
    bodyType: [],
    astrologicalSign: [],
    relationshipStatus: ["Single"],
    veteranStatus: ["Army veteran"],
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
};
