export const stateList = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const ageGrpList = [
  "10-19",
  "20-29",
  "30-39",
  "40-49",
  "50-59",
  "60-69",
  "70-79",
  "80-89",
  "90-99",
  "100-109",
];

export const genderList = [
  "Male",
  "Female",
  "Transgender Male to Female",
  "Transgender Females to Male",
  "Gender Non Conforming/Non binary",
  "Other",
];

export const orientationList = [
  "LGBTQ+",
  "Transgender",
  "Straight",
  "Lesbian",
  "Gay",
  "Bi-Sexual",
  "Other",
];

export const educationList = [
  "Less than HS Diploma or GED",
  "HS Diploma or GED",
  "Trade Certification",
  "Associates degree",
  "Bachelors degree",
  "Masters degree",
  "Doctorate",
  "Other",
];

export const raceList = [
  "American Indian/Alaskan Native",
  "Asian American",
  "Black/African American",
  "Hispanic/Latino American",
  "Native Hawaiian/Pacific Islander",
  "White",
  "Multiracial",
  "Other",
];

export const hairColorList = [
  "Bald",
  "Black",
  "Blonde",
  "Brown",
  "Gray",
  "Red",
  "Salt and Pepper",
  "Other",
];

export const eyeColorList = [
  "Black",
  "Blue",
  "Brown",
  "Green",
  "Hazel",
  "Other",
];

export const religiousPrefList = [
  "Agnostic",
  "Atheist",
  "Baptist",
  "Buddhist",
  "Catholic",
  "Christian",
  "Hindu",
  "Jewish",
  "Lutheran",
  "Methodist",
  "Mormon",
  "Muslim",
  "Native American",
  "Nondenominational",
  "Pagan",
  "Presbyterian",
  "Protestant",
  "Spiritual",
  "Wiccan",
  "Other",
];

export const bodyTypeList = [
  "Slim/Slender",
  "Athletic",
  "Average",
  "Large",
  "Husky",
  "Thin",
];

export const astrologicalSignList = [
  "Capricorn",
  "Aquarius",
  "Pisces",
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio ",
  "Sagittarius",
];

export const relationShipStatusList = [
  "Single",
  "Married",
  "Divorced",
  "Widowed/Widower",
  "In a relationship",
  "Other",
];

export const veteranStatusList = [
  "Never served",
  "Army veteran",
  "Air force veteran",
  "Navy veteran",
  "Space force veteran",
  "Coast guard veteran",
  "Marine veteran",
  "National guard veteran",
];

export const institutionalEmailProviderList = [
  "Securus Technologies",
  "Jpay",
  "Getting Out",
  "GTL",
  "Corrlincs",
  "Other",
];

export const hobbies = [
  "Crocheting",
  "Sewing",
  "Drawing",
  "Painting",
  "Model Building",
  "Hiking",
  "Biking",
  "Travelling",
  "Sightseeing",
  "Photography",
  "Videogaming",
  "Quilting",
  "Writing",
  "Card Games",
  "Others",
];

export const sports = [
  "Football",
  "Basketball",
  "Soccer",
  "Swimming",
  "Tennis",
  "Baseball",
  "Lacrosse",
  "Hockey",
  "Racing",
  "Wrestling",
  "Golf",
  "Others",
];
export const likes = [
  "Fast Food",
  "Politics",
  "Tattoos",
  "Concerts",
  "Night Clubs",
  "Movie theaters",
  "Exercise",
  "Dance",
  "Sing",
  "Post on Social Media",
  "Puzzles",
  "Reading Books",
  "Hanging with friends",
  "Staying home",
  "Dogs",
  "Cats",
  "Music",
  "Others",
];
export const personality = [
  "Shy",
  "Outgoing",
  "Funny",
  "Good listener",
  "Work well with others",
  "Organized",
  "Messy",
  "Like routines",
  "Serious",
  "Humble",
  "Arrogant",
  "Quiet",
  "Loud",
  "Smart",
  "Others",
];
export const bookGenres = [
  "Educational",
  "Biography",
  "Autobiography",
  "Thrillers",
  "Mystery",
  "Romance",
  "Western",
  "Horror",
  "Adventure",
  "True Crime",
  "Crime",
  "Fictional",
  "Non fictional",
  "Science Fiction",
  "Romance",
  "Drama",
  "Faith",
  "Others",
];
export const musicGenres = [
  "Classic Rock",
  "Soft Rock",
  "Pop",
  "Rap",
  "Hip Hop",
  "Country",
  "Classical",
  "Jazz",
  "Blues",
  "Alternative",
  "Soul/R and B",
  "Rock",
  "Reggae",
  "Latin",
  "Christian/Gospel",
  "Others",
];

export const movieGenres = [
  "Action",
  "Comedy",
  "Drama",
  "Romance",
  "Mystery",
  "Thriller",
  "Horror",
  "Animation",
  "Adventure",
  "Crime",
  "Documentary",
  "Fantasy",
  "History",
  "Sports",
  "Science Fiction",
  "Western",
  "Faith",
  "Family",
  "Romantic Comedy",
  "Others",
];

export const spokenLanguagesList = [
  "English",
  "Mandarin Chinese",
  "Hindi",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Yue Chinese (Cantonese)",
  "Vietnamese",
  "Korean",
  "Other",
];

export const fieldOptionMap = {
  Hobbies: hobbies,
  Sports: sports,
  Likes: likes,
  Personality: personality,
  BookGenres: bookGenres,
  MusicGenres: musicGenres,
  MovieGenres: movieGenres,
};

export const fieldStateNameMap = {
  Hobbies: "hobbies",
  Sports: "sports",
  Likes: "likes",
  Personality: "personality",
  BookGenres: "bookGenres",
  MusicGenres: "musicGenres",
  MovieGenres: "movieGenres",
};

export const basicInfoFieldLabelMap = {
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  inmateNumber: "Inmate #",
  age: "Age",
  gender: "Gender",
  orientation: "Orientation",
  city: "City",
  state: "State",
  mailingAddress: "Mailing Address",
  zipcode: "Zip Code",
  dateOfBirth: "Date of birth",
  height: "Height(Inches)",
  weight: "Weight (Pounds)",
  hairColor: "Hair Color",
  eyeColor: "Eye Color",
  religiousPref: "Religious Preference",
  spokenLanguages: "Spoken Languages",
  highSchool: "High School",
  highSchoolState: "High School State",
  highSchoolCity: "High School City",
  homeTownCity: "Home Town City",
  homeTownState: "Home Town State",
  education: "Education",
  collegeName: "College Name",
  collegeState: "College State",
  collegeCity: "College City",
  race: "Race",
  bodyType: "Body Type",
  astrologicalSign: "Astrological Sign",
  relationShipStatus: "RelationShip Status",
  veteranStatus: "Veteran Status",
  institutionalEmailProvider: "Institutional Email Provider",
  referredBy: "Referred By",
  bio: "Bio",
};

export const basicInfoPlaceholderMap = {
  firstName: "John",
  lastName: "Doe",
  email: "johndoe@gmail.com",
  inmateNumber: "7283",
  age: "30",
  gender: "Male",
  orientation: "Heterosexual",
  city: "New York",
  state: "NY",
  mailingAddress: "123 Main St, Apt 4B",
  zipcode: "59499",
  dateOfBirth: "1990-01-01",
  height: "6",
  weight: "180",
  hairColor: "Brown",
  eyeColor: "Blue",
  religiousPref: "Christianity",
  spokenLanguages: "English",
  highSchool: "Springfield High School",
  highSchoolState: "Illinois",
  highSchoolCity: "Springfield",
  education: "Bachelor's Degree",
  collegeName: "University of California, Berkeley",
  collegeState: "California",
  collegeCity: "Berkeley",
  homeTownCity: "Austin",
  homeTownState: "Texas",
  nameOfCollege: "Harvard University",
  race: "Caucasian",
  bodyType: "Athletic",
  astrologicalSign: "Gemini",
  relationShipStatus: "Single",
  veteranStatus: "Veteran",
  institutionalEmailProvider: "john.doe@institution.edu",
  referredBy: "user creating the customer",
  bio: "hello, I like to watch football",
};

export const basicInfoReqFieldMap = {
  firstName: true,
  lastName: true,
  email: true,
  age: true,
  gender: true,
  orientation: true,
  city: true,
  state: true,
  mailingAddress: true,
  dateOfBirth: true,
  height: true,
  weight: true,
  hairColor: true,
  eyeColor: true,
  religiousPref: false,
  spokenLanguages: true,
  education: false,
  nameOfCollege: false,
  race: true,
  bodyType: false,
  astrologicalSign: false,
  relationShipStatus: false,
  veteranStatus: false,
  referredBy: true,
  bio: false,
  imageUrl: false,
  inmateNumber: true,
  zipcode: true,
  institutionalEmailProvider: true,
};

export const basicInfoOptionsField = [
  "state",
  "gender",
  "orientation",
  "hairColor",
  "eyeColor",
  "religiousPref",
  "education",
  "race",
  "bodyType",
  "spokenLanguages",
  "astrologicalSign",
  "relationShipStatus",
  "veteranStatus",
  "institutionalEmailProvider",
];

export const basicInfoFieldDropdownOptions = {
  state: stateList,
  gender: genderList,
  orientation: orientationList,
  hairColor: hairColorList,
  eyeColor: eyeColorList,
  religiousPref: religiousPrefList,
  education: educationList,
  spokenLanguages: spokenLanguagesList,
  race: raceList,
  bodyType: bodyTypeList,
  astrologicalSign: astrologicalSignList,
  relationShipStatus: relationShipStatusList,
  veteranStatus: veteranStatusList,
  institutionalEmailProvider: institutionalEmailProviderList,
};
